# Generated by Django 2.2 on 2020-06-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hellocustomer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=30),
        ),
        migrations.AlterField(
            model_name='hellocustomer',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='hellocustomer',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='hellocustomer',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
